### PR TITLE
Update NCCL test_template container

### PR DESCRIPTION
**Pull request by lappazos**
## Summary
Update NCCL test_template container

## Test Plan
Passed full installation + test on real system.

**Commands**
```
python ./cloudaix.py --mode install --system_config_path conf/v0.6/general/system/<>.toml
python ./cloudaix.py --mode run --system_config_path conf/v0.6/general/system/<>.toml--test_scenario_path conf/v0.6/general/test_scenario/nccl_test_shortend.toml
```

### CODE REVIEW

**Comment by srinivas212** [comment]
lgtm. we can merge once we test it and know it works.

**Comment by TaekyungHeo** [comment]
This docker image does not support the NCCL bisection test. Is it okay?

**Comment by srinivas212** [comment]
> This docker image does not support the NCCL bisection test. Is it okay?

For that we need to upstream bisection and get it into pytorch or maintain our own images in ngc etc. Both of which will take time. It makes sense to merge this and have a public image for most use cases.

**Comment by lappazos** [comment]
@srinivas212 @TaekyungHeo please review

**Comment by lappazos** [comment]
> This docker image does not support the NCCL bisection test. Is it okay?

No option to add bisection into CloudAI, only CloudAIx. There its exist.

**Comment by TaekyungHeo** [comment]
Confirmed that it has NCCL 2.19: https://arc.net/l/quote/ccuzygux. Link shared by @lappazos.

**Review by TaekyungHeo — APPROVED** [review]
LGTM. Let Srinivas review and merge.

**Comment by lappazos** [comment]
> Confirmed that it has NCCL 2.19: https://arc.net/l/quote/ccuzygux. Link shared by @lappazos.

https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-02.html

**Comment by TaekyungHeo** [comment]
We may need to obfuscate sensitive terms in the PR summary. Let's wait for @srinivas212 .

**Pull request merged**
