### PR TITLE
Fix bug where tests were not correctly filtered in test_no_scenario

### PR DESCRIPTION
**Pull request by TaekyungHeo**
## Summary
Fix bug where tests were not correctly filtered in test_no_scenario. Please confirm if it would work, @amaslenn.

## Test Plan
CI passes

### CODE REVIEW

**Review by amaslenn — COMMENTED** [review]
You are changing the behaviour, if no `--test-scenario` specified, we should return _all_ available tests

`cloudai install --system-config ... --tests-dir ...` should install everything for all tests, with this change it will install nothing.

`cloudai install --system-config ... --tests-dir ... --test-scenario ...` should run installation only for tests used in the scenario, this is an optimisation to save time and space.

**Comment by TaekyungHeo** [comment]
I see, thanks @amaslenn . I will close this PR.

**Comment by TaekyungHeo** [comment]
@amaslenn Do we still need the following lines?
```
        fake_scenario = Mock()
        fake_scenario.tests = [Mock()]
        fake_scenario.tests[0].name = "test-1"
```

**Comment by amaslenn** [comment]
> @amaslenn Do we still need the following lines?

I don't know, you can try removing it: if everything still works fine, feel free to remove.

**Pull request closed without merging**
