### PR TITLE
Update TestScenarioParser to support descriptive test names

### PR DESCRIPTION
**Pull request by TaekyungHeo**
## Summary
This PR updates the `TestScenarioParser` to enhance naming conventions for test scenarios, allowing for more descriptive and flexible test names.

**Key Changes:**
1. Remove Uppermost `Tests` Section: Top-level section names are now considered test names.
2. New Naming Convention: 
   - Test names can no longer be in the format `Tests.index` (e.g., `Tests.1`).
   - The dot (`.`) is now used as a delimiter to identify sections and nesting. Having dots in names is not allowed anymore. The underscore (`_`) is preferred.

**Impact:**
- Backward Incompatibility: All existing test names must be updated to the new format.

## Test Plan
**1. Added unit tests
2. Ran on a real system**
```
$ python ./cloudaix.py...
Test Scenario: ucc_test

Section Name: 16_nodes
  Test Name: ucc_test_alltoall
  Description: alltoall
  No dependencies

Section Name: 32_nodes
  Test Name: ucc_test_alltoall
  Description: alltoall
  Start Post Comp: 16_nodes, Time: 0 seconds

Section Name: 48_nodes
  Test Name: ucc_test_alltoall
  Description: alltoall
  Start Post Comp: 32_nodes, Time: 0 seconds

Section Name: 64_nodes
  Test Name: ucc_test_alltoall
  Description: alltoall
  Start Post Comp: 48_nodes, Time: 0 seconds

Section Name: full_scale
  Test Name: ucc_test_alltoall
  Description: alltoall
  Start Post Comp: 64_nodes, Time: 0 seconds
```

### CODE REVIEW

**Comment by amaslenn** [comment]
Can we use TOML specific format (https://toml.io/en/v1.0.0#array-of-tables) here?
```toml
[[Tests]]
name = "nccl"

[[Tests]]
name = "nemo"
```

It is parsed as `{'Tests': [{'name': 'nccl'}, {'name': 'nemo'}]}`

**Comment by TaekyungHeo** [comment]
Thank you for your proposal, @amaslenn. I believe the format proposed by this PR should be sufficient for our purposes. Do you see any advantages in using the TOML array of tables?

cc: @srinivas212

**Comment by amaslenn** [comment]
> Do you see any advantages in using the TOML array of tables?

Yes, I do: using standard tools and syntax should simplify parsing and at some point we might use a schema to automatically verify all our config files.

**Comment by TaekyungHeo** [comment]
Please review and decide, @srinivas212. Either works for me.

**Pull request closed without merging**
