### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by amaslenn**
1. Add initial CI using GitHub Actions.
2. Add `.gitignore` file.

### CODE REVIEW

**Comment by x41lakazam** [comment]
Hey,

I think the names of the workflows should follow a convention

For example see [SSW rules](https://www.ssw.com.au/rules/workflow-naming-scheme/)

**Comment by amaslenn** [comment]
> I think the names of the workflows should follow a convention

Interesting link, thanks for sharing!

Could you please suggest such a name? Personally, I see `ci.yml` as "this is the main pipeline for all PRs", but will be happy to make it easy to understand for everyone.

**Comment by x41lakazam** [comment]
In my opinion there shouldn't be any "main" PR workflow as it should stay modular and workflows should have specific jobs and let the possibility to be trigger by any event independently
To me this file should be split into `lint.yml` and `test.yml`

**Comment by amaslenn** [comment]
> In my opinion there shouldn't be any "main" PR workflow as it should stay modular and workflows should have specific jobs and let the possibility to be trigger by any event independently To me this file should be split into `lint.yml` and `test.yml`

At this point it looks like a complication without adding much value. Yet we might want to follow this modular approach if pipelines will grow in size and complexity.

**Review by TaekyungHeo — APPROVED** [review]

**Pull request merged**
