### PR TITLE
Add credentials for NGC to README

### PR DESCRIPTION
**Pull request by lappazos**
## Summary
Add additional information to user on needed step to add required credentials to NGC containers.

## Additional Notes
Following #21

### CODE REVIEW

**Comment by srinivas212** [comment]
Should this go under https://github.com/NVIDIA/cloudai/blob/main/USER_GUIDE.md instead?

**Comment by lappazos** [comment]
> Should this go under https://github.com/NVIDIA/cloudai/blob/main/USER_GUIDE.md instead?

I believe it belongs to README, as it is a required part of the needed step for installation. Also, README is the first document you encounter when opening the repo. Some users asked me how to do that. But also USER_GUIDE can fit, so whatever you decide. which one should it be?

**Comment by lappazos** [comment]
@TaekyungHeo please review as well

**Review by TaekyungHeo — APPROVED** [review]
LGTM. Approved. Let's wait for Srinivas to discuss, update, and merge.

I believe having this in the README is better for users.

**Pull request merged**
